# TCL File Generated by Component Editor 13.0sp1
# Sun May 01 16:11:46 PDT 2022
# DO NOT MODIFY


# 
# avalon_rgb2gray_core "Avalon MM RGB to Gray Core" v1.0
# Heqing Huang 2022.05.01.16:11:46
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avalon_rgb2gray_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_rgb2gray_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Display
set_module_property AUTHOR "Heqing Huang"
set_module_property DISPLAY_NAME "Avalon MM RGB to Gray Core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rgb2gray_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file rgb2gray_core.sv SYSTEM_VERILOG PATH rgb2gray_core.sv TOP_LEVEL_FILE
add_fileset_file rgb2gray_gen.sv SYSTEM_VERILOG PATH rgb2gray_gen.sv


# 
# parameters
# 
add_parameter RSIZE INTEGER 4 "Red color size"
set_parameter_property RSIZE DEFAULT_VALUE 4
set_parameter_property RSIZE DISPLAY_NAME RSIZE
set_parameter_property RSIZE TYPE INTEGER
set_parameter_property RSIZE UNITS None
set_parameter_property RSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RSIZE DESCRIPTION "Red color size"
set_parameter_property RSIZE HDL_PARAMETER true
add_parameter GSIZE INTEGER 4 "Green color size"
set_parameter_property GSIZE DEFAULT_VALUE 4
set_parameter_property GSIZE DISPLAY_NAME GSIZE
set_parameter_property GSIZE TYPE INTEGER
set_parameter_property GSIZE UNITS None
set_parameter_property GSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property GSIZE DESCRIPTION "Green color size"
set_parameter_property GSIZE HDL_PARAMETER true
add_parameter BSIZE INTEGER 4 "Blue color size"
set_parameter_property BSIZE DEFAULT_VALUE 4
set_parameter_property BSIZE DISPLAY_NAME BSIZE
set_parameter_property BSIZE TYPE INTEGER
set_parameter_property BSIZE UNITS None
set_parameter_property BSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BSIZE DESCRIPTION "Blue color size"
set_parameter_property BSIZE HDL_PARAMETER true
add_parameter RGB_SIZE INTEGER 12 "RGB color size"
set_parameter_property RGB_SIZE DEFAULT_VALUE 12
set_parameter_property RGB_SIZE DISPLAY_NAME RGB_SIZE
set_parameter_property RGB_SIZE TYPE INTEGER
set_parameter_property RGB_SIZE UNITS None
set_parameter_property RGB_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RGB_SIZE DESCRIPTION "RGB color size"
set_parameter_property RGB_SIZE HDL_PARAMETER true


# 
# display items
# 
add_display_item "" "VGA Parameter" GROUP ""
add_display_item "" "Color Parameter" GROUP ""


# 
# connection point avalon
# 
add_interface avalon avalon end
set_interface_property avalon addressUnits SYMBOLS
set_interface_property avalon associatedClock clk
set_interface_property avalon associatedReset rst
set_interface_property avalon bitsPerSymbol 8
set_interface_property avalon burstOnBurstBoundariesOnly false
set_interface_property avalon burstcountUnits WORDS
set_interface_property avalon explicitAddressSpan 0
set_interface_property avalon holdTime 0
set_interface_property avalon linewrapBursts false
set_interface_property avalon maximumPendingReadTransactions 0
set_interface_property avalon readLatency 0
set_interface_property avalon readWaitTime 1
set_interface_property avalon setupTime 0
set_interface_property avalon timingUnits Cycles
set_interface_property avalon writeWaitTime 0
set_interface_property avalon ENABLED true
set_interface_property avalon EXPORT_OF ""
set_interface_property avalon PORT_NAME_MAP ""
set_interface_property avalon SVD_ADDRESS_GROUP ""

add_interface_port avalon avs_write write Input 1
add_interface_port avalon avs_address address Input 1
add_interface_port avalon avs_writedata writedata Input 32
set_interface_assignment avalon embeddedsw.configuration.isFlash 0
set_interface_assignment avalon embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point src_rgb
# 
add_interface src_rgb avalon_streaming end
set_interface_property src_rgb associatedClock clk
set_interface_property src_rgb associatedReset rst
set_interface_property src_rgb dataBitsPerSymbol 12
set_interface_property src_rgb errorDescriptor ""
set_interface_property src_rgb firstSymbolInHighOrderBits true
set_interface_property src_rgb maxChannel 0
set_interface_property src_rgb readyLatency 0
set_interface_property src_rgb ENABLED true
set_interface_property src_rgb EXPORT_OF ""
set_interface_property src_rgb PORT_NAME_MAP ""
set_interface_property src_rgb SVD_ADDRESS_GROUP ""

add_interface_port src_rgb src_rgb data Input RGB_SIZE


# 
# connection point sink_rgb
# 
add_interface sink_rgb avalon_streaming start
set_interface_property sink_rgb associatedClock clk
set_interface_property sink_rgb associatedReset rst
set_interface_property sink_rgb dataBitsPerSymbol 12
set_interface_property sink_rgb errorDescriptor ""
set_interface_property sink_rgb firstSymbolInHighOrderBits true
set_interface_property sink_rgb maxChannel 0
set_interface_property sink_rgb readyLatency 0
set_interface_property sink_rgb ENABLED true
set_interface_property sink_rgb EXPORT_OF ""
set_interface_property sink_rgb PORT_NAME_MAP ""
set_interface_property sink_rgb SVD_ADDRESS_GROUP ""

add_interface_port sink_rgb snk_rgb data Output RGB_SIZE

