# TCL File Generated by Component Editor 13.0sp1
# Mon May 02 12:39:21 PDT 2022
# DO NOT MODIFY


# 
# video_daisy_system "Video Daisy System" v1.0
# Heqing Huang 2022.05.02.12:39:21
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module video_daisy_system
# 
set_module_property DESCRIPTION ""
set_module_property NAME video_daisy_system
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Display
set_module_property AUTHOR "Heqing Huang"
set_module_property DISPLAY_NAME "Video Daisy System"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL video_daisy_system
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file vga_timing.svh SYSTEM_VERILOG_INCLUDE PATH ../vga_core/vga_timing.svh
add_fileset_file vga_async_fifo.sv SYSTEM_VERILOG PATH ../vga_core/vga_async_fifo.sv
add_fileset_file vga_dsync.sv SYSTEM_VERILOG PATH ../vga_core/vga_dsync.sv
add_fileset_file vga_frame_counter.sv SYSTEM_VERILOG PATH ../vga_core/vga_frame_counter.sv
add_fileset_file vga_line_buffer.sv SYSTEM_VERILOG PATH ../vga_core/vga_line_buffer.sv
add_fileset_file vga_sync.sv SYSTEM_VERILOG PATH ../vga_core/vga_sync.sv
add_fileset_file vga_sync_core.sv SYSTEM_VERILOG PATH ../vga_core/vga_sync_core.sv
add_fileset_file video_bar_core.sv SYSTEM_VERILOG PATH ../video_core/bar_core/video_bar_core.sv
add_fileset_file video_bar_gen.sv SYSTEM_VERILOG PATH ../video_core/bar_core/video_bar_gen.sv
add_fileset_file video_daisy_system.sv SYSTEM_VERILOG PATH video_daisy_system.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter RSIZE INTEGER 4
set_parameter_property RSIZE DEFAULT_VALUE 4
set_parameter_property RSIZE DISPLAY_NAME RSIZE
set_parameter_property RSIZE TYPE INTEGER
set_parameter_property RSIZE UNITS None
set_parameter_property RSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RSIZE HDL_PARAMETER true
add_parameter GSIZE INTEGER 4
set_parameter_property GSIZE DEFAULT_VALUE 4
set_parameter_property GSIZE DISPLAY_NAME GSIZE
set_parameter_property GSIZE TYPE INTEGER
set_parameter_property GSIZE UNITS None
set_parameter_property GSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property GSIZE HDL_PARAMETER true
add_parameter BSIZE INTEGER 4
set_parameter_property BSIZE DEFAULT_VALUE 4
set_parameter_property BSIZE DISPLAY_NAME BSIZE
set_parameter_property BSIZE TYPE INTEGER
set_parameter_property BSIZE UNITS None
set_parameter_property BSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BSIZE HDL_PARAMETER true
add_parameter RGB_SIZE INTEGER 12
set_parameter_property RGB_SIZE DEFAULT_VALUE 12
set_parameter_property RGB_SIZE DISPLAY_NAME RGB_SIZE
set_parameter_property RGB_SIZE TYPE INTEGER
set_parameter_property RGB_SIZE UNITS None
set_parameter_property RGB_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RGB_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avs_video_bar_core
# 
add_interface avs_video_bar_core avalon end
set_interface_property avs_video_bar_core addressUnits SYMBOLS
set_interface_property avs_video_bar_core associatedClock sys_clk
set_interface_property avs_video_bar_core associatedReset sys_rst
set_interface_property avs_video_bar_core bitsPerSymbol 8
set_interface_property avs_video_bar_core burstOnBurstBoundariesOnly false
set_interface_property avs_video_bar_core burstcountUnits WORDS
set_interface_property avs_video_bar_core explicitAddressSpan 0
set_interface_property avs_video_bar_core holdTime 0
set_interface_property avs_video_bar_core linewrapBursts false
set_interface_property avs_video_bar_core maximumPendingReadTransactions 0
set_interface_property avs_video_bar_core readLatency 0
set_interface_property avs_video_bar_core readWaitTime 1
set_interface_property avs_video_bar_core setupTime 0
set_interface_property avs_video_bar_core timingUnits Cycles
set_interface_property avs_video_bar_core writeWaitTime 0
set_interface_property avs_video_bar_core ENABLED true
set_interface_property avs_video_bar_core EXPORT_OF ""
set_interface_property avs_video_bar_core PORT_NAME_MAP ""
set_interface_property avs_video_bar_core SVD_ADDRESS_GROUP ""

add_interface_port avs_video_bar_core avs_video_bar_core_address address Input 1
add_interface_port avs_video_bar_core avs_video_bar_core_write write Input 1
add_interface_port avs_video_bar_core avs_video_bar_core_writedata writedata Input 32
set_interface_assignment avs_video_bar_core embeddedsw.configuration.isFlash 0
set_interface_assignment avs_video_bar_core embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_video_bar_core embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_video_bar_core embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pixel_clk
# 
add_interface pixel_clk clock end
set_interface_property pixel_clk clockRate 0
set_interface_property pixel_clk ENABLED true
set_interface_property pixel_clk EXPORT_OF ""
set_interface_property pixel_clk PORT_NAME_MAP ""
set_interface_property pixel_clk SVD_ADDRESS_GROUP ""

add_interface_port pixel_clk pixel_clk clk Input 1


# 
# connection point pixel_rst
# 
add_interface pixel_rst reset end
set_interface_property pixel_rst associatedClock pixel_clk
set_interface_property pixel_rst synchronousEdges DEASSERT
set_interface_property pixel_rst ENABLED true
set_interface_property pixel_rst EXPORT_OF ""
set_interface_property pixel_rst PORT_NAME_MAP ""
set_interface_property pixel_rst SVD_ADDRESS_GROUP ""

add_interface_port pixel_rst pixel_rst reset Input 1


# 
# connection point sys_clk
# 
add_interface sys_clk clock end
set_interface_property sys_clk clockRate 0
set_interface_property sys_clk ENABLED true
set_interface_property sys_clk EXPORT_OF ""
set_interface_property sys_clk PORT_NAME_MAP ""
set_interface_property sys_clk SVD_ADDRESS_GROUP ""

add_interface_port sys_clk sys_clk clk Input 1


# 
# connection point sys_rst
# 
add_interface sys_rst reset end
set_interface_property sys_rst associatedClock sys_clk
set_interface_property sys_rst synchronousEdges DEASSERT
set_interface_property sys_rst ENABLED true
set_interface_property sys_rst EXPORT_OF ""
set_interface_property sys_rst PORT_NAME_MAP ""
set_interface_property sys_rst SVD_ADDRESS_GROUP ""

add_interface_port sys_rst sys_rst reset Input 1


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock pixel_clk
set_interface_property vga associatedReset pixel_rst
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga vga_r export Output RSIZE
add_interface_port vga vga_g export Output GSIZE
add_interface_port vga vga_b export Output BSIZE
add_interface_port vga vga_hsync export Output 1
add_interface_port vga vga_vsync export Output 1

