# TCL File Generated by Component Editor 13.0sp1
# Wed Apr 27 00:05:44 PDT 2022
# DO NOT MODIFY


#
# avalon_sdram_controller "Avalon MM Sdram Controller" v1.0
# Heqing Huang 2022.04.27.00:05:44
#
#

#
# request TCL package from ACDS 13.1
#
package require -exact qsys 13.1


#
# module avalon_sdram_controller
#
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sdram_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Memories and Memory Controllers/External Memory Interfaces/SDRAM Interfaces"
set_module_property AUTHOR "Heqing Huang"
set_module_property DISPLAY_NAME "Avalon MM Sdram Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property VALIDATION_CALLBACK validate

#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_sdram_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_sdram_controller.sv SYSTEM_VERILOG PATH avalon_sdram_controller.sv TOP_LEVEL_FILE
add_fileset_file sdram_access.sv SYSTEM_VERILOG PATH sdram_access.sv
add_fileset_file sdram_fifo.sv SYSTEM_VERILOG PATH sdram_fifo.sv
add_fileset_file sdram_init.sv SYSTEM_VERILOG PATH sdram_init.sv
add_fileset_file sdram_localparams.svh SYSTEM_VERILOG_INCLUDE PATH sdram_localparams.svh


#
# parameters
#
add_parameter CMD_FIFO_SIZE INTEGER 4 ""
set_parameter_property CMD_FIFO_SIZE DEFAULT_VALUE 4
set_parameter_property CMD_FIFO_SIZE DISPLAY_NAME "command fifo Size"
set_parameter_property CMD_FIFO_SIZE TYPE INTEGER
set_parameter_property CMD_FIFO_SIZE UNITS None
set_parameter_property CMD_FIFO_SIZE ALLOWED_RANGES {1 2 4 8 16 32 64}
set_parameter_property CMD_FIFO_SIZE DESCRIPTION ""
set_parameter_property CMD_FIFO_SIZE HDL_PARAMETER true
add_parameter WRITE_FIFO_SIZE INTEGER 4
set_parameter_property WRITE_FIFO_SIZE DEFAULT_VALUE 4
set_parameter_property WRITE_FIFO_SIZE DISPLAY_NAME "write data fifo Size"
set_parameter_property WRITE_FIFO_SIZE TYPE INTEGER
set_parameter_property WRITE_FIFO_SIZE UNITS None
set_parameter_property WRITE_FIFO_SIZE ALLOWED_RANGES {1 2 4 8 16 32 64}
set_parameter_property WRITE_FIFO_SIZE HDL_PARAMETER true
add_parameter READ_FIFO_SIZE INTEGER 4
set_parameter_property READ_FIFO_SIZE DEFAULT_VALUE 4
set_parameter_property READ_FIFO_SIZE DISPLAY_NAME "read data fifo Size"
set_parameter_property READ_FIFO_SIZE TYPE INTEGER
set_parameter_property READ_FIFO_SIZE UNITS None
set_parameter_property READ_FIFO_SIZE ALLOWED_RANGES {1 2 4 8 16 32 64}
set_parameter_property READ_FIFO_SIZE HDL_PARAMETER true
add_parameter AVS_DW INTEGER 16
set_parameter_property AVS_DW DEFAULT_VALUE 16
set_parameter_property AVS_DW DISPLAY_NAME "avalon bus data width"
set_parameter_property AVS_DW TYPE INTEGER
set_parameter_property AVS_DW UNITS None
set_parameter_property AVS_DW ALLOWED_RANGES 1:1000
set_parameter_property AVS_DW HDL_PARAMETER true
add_parameter AVS_AW INTEGER 25
set_parameter_property AVS_AW DEFAULT_VALUE 25
set_parameter_property AVS_AW DISPLAY_NAME "avalon bus address width"
set_parameter_property AVS_AW TYPE INTEGER
set_parameter_property AVS_AW UNITS None
set_parameter_property AVS_AW ALLOWED_RANGES 1:1000
set_parameter_property AVS_AW HDL_PARAMETER true
add_parameter SDRAM_DATA INTEGER 16
set_parameter_property SDRAM_DATA DEFAULT_VALUE 16
set_parameter_property SDRAM_DATA DISPLAY_NAME "SDRAM data width"
set_parameter_property SDRAM_DATA TYPE INTEGER
set_parameter_property SDRAM_DATA UNITS Bits
set_parameter_property SDRAM_DATA ALLOWED_RANGES {8 16 32 64}
set_parameter_property SDRAM_DATA HDL_PARAMETER true
add_parameter SDRAM_BANK INTEGER 4
set_parameter_property SDRAM_BANK DEFAULT_VALUE 4
set_parameter_property SDRAM_BANK DISPLAY_NAME "SDRAM number of bank"
set_parameter_property SDRAM_BANK TYPE INTEGER
set_parameter_property SDRAM_BANK UNITS None
set_parameter_property SDRAM_BANK ALLOWED_RANGES {2 4}
set_parameter_property SDRAM_BANK HDL_PARAMETER true
add_parameter SDRAM_ROW INTEGER 13
set_parameter_property SDRAM_ROW DEFAULT_VALUE 13
set_parameter_property SDRAM_ROW DISPLAY_NAME "SDRAM number of row"
set_parameter_property SDRAM_ROW TYPE INTEGER
set_parameter_property SDRAM_ROW UNITS None
set_parameter_property SDRAM_ROW ALLOWED_RANGES 1:64
set_parameter_property SDRAM_ROW HDL_PARAMETER true
add_parameter SDRAM_COL INTEGER 9
set_parameter_property SDRAM_COL DEFAULT_VALUE 9
set_parameter_property SDRAM_COL DISPLAY_NAME "SDRAM number of column"
set_parameter_property SDRAM_COL TYPE INTEGER
set_parameter_property SDRAM_COL UNITS None
set_parameter_property SDRAM_COL ALLOWED_RANGES 1:64
set_parameter_property SDRAM_COL HDL_PARAMETER true
add_parameter SDRAM_BA INTEGER 2
set_parameter_property SDRAM_BA DEFAULT_VALUE 2
set_parameter_property SDRAM_BA DISPLAY_NAME "SDRAM ba width"
set_parameter_property SDRAM_BA TYPE INTEGER
set_parameter_property SDRAM_BA UNITS None
set_parameter_property SDRAM_BA ALLOWED_RANGES 1:64
set_parameter_property SDRAM_BA HDL_PARAMETER true
add_parameter SDRAM_BL INTEGER 1
set_parameter_property SDRAM_BL DEFAULT_VALUE 1
set_parameter_property SDRAM_BL DISPLAY_NAME "SDRAM burst length"
set_parameter_property SDRAM_BL TYPE INTEGER
set_parameter_property SDRAM_BL UNITS None
set_parameter_property SDRAM_BL ALLOWED_RANGES {1 2 4 8}
set_parameter_property SDRAM_BL HDL_PARAMETER true
add_parameter INIT_REF_CNT INTEGER 2
set_parameter_property INIT_REF_CNT DEFAULT_VALUE 2
set_parameter_property INIT_REF_CNT DISPLAY_NAME "Number of refresh operation in initialization process"
set_parameter_property INIT_REF_CNT TYPE INTEGER
set_parameter_property INIT_REF_CNT UNITS None
set_parameter_property INIT_REF_CNT ALLOWED_RANGES {1 2 3}
set_parameter_property INIT_REF_CNT HDL_PARAMETER true
add_parameter CL INTEGER 2
set_parameter_property CL DEFAULT_VALUE 2
set_parameter_property CL DISPLAY_NAME CL
set_parameter_property CL TYPE INTEGER
set_parameter_property CL UNITS None
set_parameter_property CL ALLOWED_RANGES {2 3}
set_parameter_property CL HDL_PARAMETER true
add_parameter tINIT INTEGER 100
set_parameter_property tINIT DEFAULT_VALUE 100
set_parameter_property tINIT DISPLAY_NAME "Initialization time (tINIT)"
set_parameter_property tINIT TYPE INTEGER
set_parameter_property tINIT UNITS Microseconds
set_parameter_property tINIT ALLOWED_RANGES 1:1000
set_parameter_property tINIT HDL_PARAMETER true
add_parameter tRAS INTEGER 42
set_parameter_property tRAS DEFAULT_VALUE 42
set_parameter_property tRAS DISPLAY_NAME "ACTIVE-to-PRECHARGE command (tRAS)"
set_parameter_property tRAS TYPE INTEGER
set_parameter_property tRAS UNITS Nanoseconds
set_parameter_property tRAS ALLOWED_RANGES 1:1000
set_parameter_property tRAS HDL_PARAMETER true
add_parameter tRC INTEGER 60
set_parameter_property tRC DEFAULT_VALUE 60
set_parameter_property tRC DISPLAY_NAME "ACTIVE-to-ACTIVE command period (tRC)"
set_parameter_property tRC TYPE INTEGER
set_parameter_property tRC UNITS Nanoseconds
set_parameter_property tRC ALLOWED_RANGES 1:1000
set_parameter_property tRC HDL_PARAMETER true
add_parameter tRCD INTEGER 18
set_parameter_property tRCD DEFAULT_VALUE 18
set_parameter_property tRCD DISPLAY_NAME "ACTIVE-to-READ or WRITE delay (tRCD)"
set_parameter_property tRCD TYPE INTEGER
set_parameter_property tRCD UNITS Nanoseconds
set_parameter_property tRCD ALLOWED_RANGES 1:1000
set_parameter_property tRCD HDL_PARAMETER true
add_parameter tRFC INTEGER 60
set_parameter_property tRFC DEFAULT_VALUE 60
set_parameter_property tRFC DISPLAY_NAME "AUTO REFRESH period (tRFC)"
set_parameter_property tRFC TYPE INTEGER
set_parameter_property tRFC UNITS Nanoseconds
set_parameter_property tRFC ALLOWED_RANGES 1:1000
set_parameter_property tRFC HDL_PARAMETER true
add_parameter tRP INTEGER 18
set_parameter_property tRP DEFAULT_VALUE 18
set_parameter_property tRP DISPLAY_NAME "PRECHARGE command period (tRP)"
set_parameter_property tRP TYPE INTEGER
set_parameter_property tRP UNITS Nanoseconds
set_parameter_property tRP ALLOWED_RANGES 1:1000
set_parameter_property tRP HDL_PARAMETER true
add_parameter tRRD INTEGER 12
set_parameter_property tRRD DEFAULT_VALUE 12
set_parameter_property tRRD DISPLAY_NAME "ACTIVE bank a to ACTIVE bank b command (tRRD)"
set_parameter_property tRRD TYPE INTEGER
set_parameter_property tRRD UNITS Nanoseconds
set_parameter_property tRRD ALLOWED_RANGES 1:1000
set_parameter_property tRRD HDL_PARAMETER true
add_parameter tREF INTEGER 64
set_parameter_property tREF DEFAULT_VALUE 64
set_parameter_property tREF DISPLAY_NAME "Refresh period (tREF)"
set_parameter_property tREF TYPE INTEGER
set_parameter_property tREF UNITS Milliseconds
set_parameter_property tREF ALLOWED_RANGES 1:1000
set_parameter_property tREF HDL_PARAMETER true
add_parameter CLK_PERIOD INTEGER 10
set_parameter_property CLK_PERIOD DEFAULT_VALUE 10
set_parameter_property CLK_PERIOD DISPLAY_NAME "Clock Period"
set_parameter_property CLK_PERIOD TYPE INTEGER
set_parameter_property CLK_PERIOD UNITS Nanoseconds
set_parameter_property CLK_PERIOD ALLOWED_RANGES 1:1000
set_parameter_property CLK_PERIOD HDL_PARAMETER true


# system info parameters
add_parameter clockRate LONG
set_parameter_property clockRate DEFAULT_VALUE {0}
set_parameter_property clockRate DISPLAY_NAME {clockRate}
set_parameter_property clockRate VISIBLE {0}
set_parameter_property clockRate AFFECTS_GENERATION {1}
set_parameter_property clockRate HDL_PARAMETER {0}
set_parameter_property clockRate SYSTEM_INFO {clock_rate clk}
set_parameter_property clockRate SYSTEM_INFO_TYPE {CLOCK_RATE}
set_parameter_property clockRate SYSTEM_INFO_ARG {clk}

#
# display items
#
add_display_item {} {Memory Profile} GROUP tab

add_display_item "Memory Profile" "SDRAM FIFO Size" GROUP "SDRAM FIFO"
add_display_item "SDRAM FIFO Size" CMD_FIFO_SIZE PARAMETER ""
add_display_item "SDRAM FIFO Size" WRITE_FIFO_SIZE PARAMETER ""
add_display_item "SDRAM FIFO Size" READ_FIFO_SIZE PARAMETER ""
add_display_item "Memory Profile" "Avalon Bus Parameter" GROUP ""
add_display_item "Avalon Bus Parameter" AVS_DW PARAMETER ""
add_display_item "Avalon Bus Parameter" AVS_AW PARAMETER ""
add_display_item "Memory Profile" "SDRAM Architecture" GROUP "SDRAM FIFO"
add_display_item "SDRAM Architecture" SDRAM_DATA PARAMETER ""
add_display_item "SDRAM Architecture" SDRAM_BANK PARAMETER ""
add_display_item "SDRAM Architecture" SDRAM_ROW PARAMETER ""
add_display_item "SDRAM Architecture" SDRAM_COL PARAMETER ""
add_display_item "SDRAM Architecture" SDRAM_BA PARAMETER ""
add_display_item "SDRAM Architecture" SDRAM_BL PARAMETER ""

add_display_item {} {Timing} GROUP tab

add_display_item "Timing" "SDRAM Timing" GROUP "SDRAM Timing"
add_display_item "SDRAM Timing" INIT_REF_CNT PARAMETER ""
add_display_item "SDRAM Timing" CL PARAMETER ""
add_display_item "SDRAM Timing" tINIT PARAMETER ""
add_display_item "SDRAM Timing" tRAS PARAMETER ""
add_display_item "SDRAM Timing" tRC PARAMETER ""
add_display_item "SDRAM Timing" tRCD PARAMETER ""
add_display_item "SDRAM Timing" tRFC PARAMETER ""
add_display_item "SDRAM Timing" tRP PARAMETER ""
add_display_item "SDRAM Timing" tRRD PARAMETER ""
add_display_item "SDRAM Timing" tREF PARAMETER ""
add_display_item "SDRAM Timing" CLK_PERIOD PARAMETER ""


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point avalon
#
add_interface avalon avalon end
set_interface_property avalon addressUnits SYMBOLS
set_interface_property avalon associatedClock clock
set_interface_property avalon associatedReset reset
set_interface_property avalon bitsPerSymbol 8
set_interface_property avalon burstOnBurstBoundariesOnly false
set_interface_property avalon burstcountUnits WORDS
set_interface_property avalon explicitAddressSpan 0
set_interface_property avalon holdTime 0
set_interface_property avalon isMemoryDevice true
set_interface_property avalon linewrapBursts false
set_interface_property avalon maximumPendingReadTransactions 4
set_interface_property avalon readLatency 0
set_interface_property avalon readWaitTime 1
set_interface_property avalon setupTime 0
set_interface_property avalon timingUnits Cycles
set_interface_property avalon writeWaitTime 0
set_interface_property avalon ENABLED true
set_interface_property avalon EXPORT_OF ""
set_interface_property avalon PORT_NAME_MAP ""
set_interface_property avalon SVD_ADDRESS_GROUP ""

add_interface_port avalon avs_read read Input 1
add_interface_port avalon avs_write write Input 1
add_interface_port avalon avs_address address Input AVS_AW
add_interface_port avalon avs_writedata writedata Input AVS_DW
add_interface_port avalon avs_byteenable byteenable Input AVS_DW/8
add_interface_port avalon avs_readdata readdata Output AVS_DW
add_interface_port avalon avs_waitrequest waitrequest Output 1
add_interface_port avalon avs_readdatavalid readdatavalid Output 1
set_interface_assignment avalon embeddedsw.configuration.isFlash 0
set_interface_assignment avalon embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avalon embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon embeddedsw.configuration.isPrintableDevice 0


#
# connection point sdram
#
add_interface sdram conduit end
set_interface_property sdram associatedClock ""
set_interface_property sdram associatedReset ""
set_interface_property sdram ENABLED true
set_interface_property sdram EXPORT_OF ""
set_interface_property sdram PORT_NAME_MAP ""
set_interface_property sdram SVD_ADDRESS_GROUP ""

add_interface_port sdram sdram_cs_n export Output 1
add_interface_port sdram sdram_ras_n export Output 1
add_interface_port sdram sdram_cas_n export Output 1
add_interface_port sdram sdram_we_n export Output 1
add_interface_port sdram sdram_addr export Output SDRAM_ROW
add_interface_port sdram sdram_ba export Output SDRAM_BA
add_interface_port sdram sdram_dq export Bidir SDRAM_DATA
add_interface_port sdram sdram_dqm export Output SDRAM_DATA/8
add_interface_port sdram sdram_cke export Output 1

proc validate {} {
  set clockRate [ get_parameter_value CLK_PERIOD ]
  set_module_assignment embeddedsw.CMacro.FREQ $clockRate
}
